### ISSUE TITLE
Getting started guide points to 404 page

### ISSUE THREAD

**Issue by RiRa12621** [parca-dev/docs#178]
https://github.com/parca-dev/docs/blob/8e390c39e8665d822a13f8fbe2ca6d295878861a/docs/ingestion.md?plain=1#L13

That's a dead link pointing to an o'reilly 404 page 

<img width="1672" alt="Screenshot 2022-09-29 at 17 17 43" src="https://user-images.githubusercontent.com/14996407/193071291-bd2461a1-86cb-42fc-b240-8a6ff1a54589.png">

**Comment by brancz** [comment]
We should probably just remove the link, quite a shame I liked katacoda tutorials a lot. Do you want to contribute the removal @RiRa12621?

**Comment by RiRa12621** [comment]
https://github.com/parca-dev/docs/pull/182

indeed a bit sad that katacoda doesn't exist in its pure form anymore
