### ISSUE TITLE
Screenshots URIs are dead/relocated (Grafana Flamegraph Plugin)

### ISSUE THREAD

**Issue by Venryx** [parca-dev/docs#378]
Regarding this page: https://github.com/parca-dev/docs/blob/main/docs/grafana-flamegraph-plugin.md

At the bottom there are supposed to be screenshots, but the URIs for the images resolve to 404s. I tried finding the (relocated?) images, but could not find them. Hopefully someone more familiar with the repo can know where they now exist.

**Comment by brancz** [comment]
We need to fix this, there is a core datasource in Grafana that is available without having to install any plugin. @manojVivek could you adapt the docs to use the core plugin rather than ours? https://grafana.com/docs/grafana/latest/datasources/parca/
